#!/bin/zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# NVM Configuration
export NVM_DIR="$HOME/.nvm"
 [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
 [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

source /opt/homebrew/opt/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

list_prs() {
	echo -e "\n🗓️ Ready for review 👀:" \
		&& gh pr list -S 'draft:false sort:updated-desc is:open is:pr review:required'

	echo -e "\n✅ Changes requested:" \
		&& gh pr list -S 'draft:false sort:updated-desc is:open is:pr review:changes-requested'
}

review_pull_request() {
	pr=$1
	gh pr checkout $pr
	gh pr view $pr --web
}

# Load .zshrc
alias src="source ~/.zshrc"

alias pres="open ~/Documents/PresentationLaptop.vncloc"
alias cb="cd ~/codebase"
alias cpr="cd ~/codebase/constellation; list_prs"
alias prs="list_prs"
alias review="review_pull_request"

# alias docker=podman
